// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

// Present provides a mock function with given fields: _a0
func (_m *Presenter) Present(_a0 []string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPresenter creates a new instance of Presenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Presenter {
	mock := &Presenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
